version: '3'

volumes:
  mongodb_realworld1:
  mongodb_realworld2:
  mongodb_realworld3:
  minio_realworld_storage: {}

services:
  mongodb_realworld1:
    container_name: mongodb_realworld1
    image: mongo:latest
    ports:
      - "21000:27017"
    volumes:
      - mongodb_realworld1:/data/db
      # - ./rs-init.sh:/scripts/rs-init.sh
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongodb_realworld2:
    container_name: mongodb_realworld2
    image: mongo:latest
    ports:
      - "21001:27017"
    depends_on:
      - mongodb_realworld1
    volumes:
      - mongodb_realworld2:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongodb_realworld3:
    container_name: mongodb_realworld3
    image: mongo:latest
    ports:
      - "21002:27017"
    depends_on:
      - mongodb_realworld1
    volumes:
      - mongodb_realworld3:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_realworld_storage:/data
    environment:
      MINIO_ROOT_USER: realworlduser
      MINIO_ROOT_PASSWORD: realworldpassword
    command: server --console-address ":9001" /data

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    restart: always
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    restart: always
    command: ["--config=/providerconf/otel_config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - "${PWD}/infra/providerconf:/providerconf"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    environment:
      - DD_SITE=${DD_SITE}
      - DD_API_KEY=${DD_API_KEY}
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "${PWD}/infra/providerconf/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"