// Code generated by counterfeiter. DO NOT EDIT.
package domainfakes

import (
	"context"
	"realworld-go/domain"
	"realworld-go/domain/model"
	"sync"
)

type FakeCommentRepository struct {
	CreateStub        func(context.Context, model.Comment) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 model.Comment
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteByArticleIdStub        func(context.Context, string) error
	deleteByArticleIdMutex       sync.RWMutex
	deleteByArticleIdArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteByArticleIdReturns struct {
		result1 error
	}
	deleteByArticleIdReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteByIDStub        func(context.Context, model.Comment) error
	deleteByIDMutex       sync.RWMutex
	deleteByIDArgsForCall []struct {
		arg1 context.Context
		arg2 model.Comment
	}
	deleteByIDReturns struct {
		result1 error
	}
	deleteByIDReturnsOnCall map[int]struct {
		result1 error
	}
	FindAllByArticleIDStub        func(context.Context, domain.FindAllCommentParam, ...string) ([]model.Comment, error)
	findAllByArticleIDMutex       sync.RWMutex
	findAllByArticleIDArgsForCall []struct {
		arg1 context.Context
		arg2 domain.FindAllCommentParam
		arg3 []string
	}
	findAllByArticleIDReturns struct {
		result1 []model.Comment
		result2 error
	}
	findAllByArticleIDReturnsOnCall map[int]struct {
		result1 []model.Comment
		result2 error
	}
	UpdateByIdStub        func(context.Context, model.Comment, ...string) error
	updateByIdMutex       sync.RWMutex
	updateByIdArgsForCall []struct {
		arg1 context.Context
		arg2 model.Comment
		arg3 []string
	}
	updateByIdReturns struct {
		result1 error
	}
	updateByIdReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCommentRepository) Create(arg1 context.Context, arg2 model.Comment) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 model.Comment
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeCommentRepository) CreateCalls(stub func(context.Context, model.Comment) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeCommentRepository) CreateArgsForCall(i int) (context.Context, model.Comment) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCommentRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) DeleteByArticleId(arg1 context.Context, arg2 string) error {
	fake.deleteByArticleIdMutex.Lock()
	ret, specificReturn := fake.deleteByArticleIdReturnsOnCall[len(fake.deleteByArticleIdArgsForCall)]
	fake.deleteByArticleIdArgsForCall = append(fake.deleteByArticleIdArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteByArticleIdStub
	fakeReturns := fake.deleteByArticleIdReturns
	fake.recordInvocation("DeleteByArticleId", []interface{}{arg1, arg2})
	fake.deleteByArticleIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) DeleteByArticleIdCallCount() int {
	fake.deleteByArticleIdMutex.RLock()
	defer fake.deleteByArticleIdMutex.RUnlock()
	return len(fake.deleteByArticleIdArgsForCall)
}

func (fake *FakeCommentRepository) DeleteByArticleIdCalls(stub func(context.Context, string) error) {
	fake.deleteByArticleIdMutex.Lock()
	defer fake.deleteByArticleIdMutex.Unlock()
	fake.DeleteByArticleIdStub = stub
}

func (fake *FakeCommentRepository) DeleteByArticleIdArgsForCall(i int) (context.Context, string) {
	fake.deleteByArticleIdMutex.RLock()
	defer fake.deleteByArticleIdMutex.RUnlock()
	argsForCall := fake.deleteByArticleIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCommentRepository) DeleteByArticleIdReturns(result1 error) {
	fake.deleteByArticleIdMutex.Lock()
	defer fake.deleteByArticleIdMutex.Unlock()
	fake.DeleteByArticleIdStub = nil
	fake.deleteByArticleIdReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) DeleteByArticleIdReturnsOnCall(i int, result1 error) {
	fake.deleteByArticleIdMutex.Lock()
	defer fake.deleteByArticleIdMutex.Unlock()
	fake.DeleteByArticleIdStub = nil
	if fake.deleteByArticleIdReturnsOnCall == nil {
		fake.deleteByArticleIdReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteByArticleIdReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) DeleteById(arg1 context.Context, arg2 model.Comment) error {
	fake.deleteByIDMutex.Lock()
	ret, specificReturn := fake.deleteByIDReturnsOnCall[len(fake.deleteByIDArgsForCall)]
	fake.deleteByIDArgsForCall = append(fake.deleteByIDArgsForCall, struct {
		arg1 context.Context
		arg2 model.Comment
	}{arg1, arg2})
	stub := fake.DeleteByIDStub
	fakeReturns := fake.deleteByIDReturns
	fake.recordInvocation("DeleteById", []interface{}{arg1, arg2})
	fake.deleteByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) DeleteByIDCallCount() int {
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	return len(fake.deleteByIDArgsForCall)
}

func (fake *FakeCommentRepository) DeleteByIDCalls(stub func(context.Context, model.Comment) error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = stub
}

func (fake *FakeCommentRepository) DeleteByIDArgsForCall(i int) (context.Context, model.Comment) {
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	argsForCall := fake.deleteByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCommentRepository) DeleteByIDReturns(result1 error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = nil
	fake.deleteByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) DeleteByIDReturnsOnCall(i int, result1 error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = nil
	if fake.deleteByIDReturnsOnCall == nil {
		fake.deleteByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) FindAllByArticleId(arg1 context.Context, arg2 domain.FindAllCommentParam, arg3 ...string) ([]model.Comment, error) {
	fake.findAllByArticleIDMutex.Lock()
	ret, specificReturn := fake.findAllByArticleIDReturnsOnCall[len(fake.findAllByArticleIDArgsForCall)]
	fake.findAllByArticleIDArgsForCall = append(fake.findAllByArticleIDArgsForCall, struct {
		arg1 context.Context
		arg2 domain.FindAllCommentParam
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.FindAllByArticleIDStub
	fakeReturns := fake.findAllByArticleIDReturns
	fake.recordInvocation("FindAllByArticleId", []interface{}{arg1, arg2, arg3})
	fake.findAllByArticleIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCommentRepository) FindAllByArticleIDCallCount() int {
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	return len(fake.findAllByArticleIDArgsForCall)
}

func (fake *FakeCommentRepository) FindAllByArticleIDCalls(stub func(context.Context, domain.FindAllCommentParam, ...string) ([]model.Comment, error)) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = stub
}

func (fake *FakeCommentRepository) FindAllByArticleIDArgsForCall(i int) (context.Context, domain.FindAllCommentParam, []string) {
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	argsForCall := fake.findAllByArticleIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCommentRepository) FindAllByArticleIDReturns(result1 []model.Comment, result2 error) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = nil
	fake.findAllByArticleIDReturns = struct {
		result1 []model.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeCommentRepository) FindAllByArticleIDReturnsOnCall(i int, result1 []model.Comment, result2 error) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = nil
	if fake.findAllByArticleIDReturnsOnCall == nil {
		fake.findAllByArticleIDReturnsOnCall = make(map[int]struct {
			result1 []model.Comment
			result2 error
		})
	}
	fake.findAllByArticleIDReturnsOnCall[i] = struct {
		result1 []model.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeCommentRepository) UpdateById(arg1 context.Context, arg2 model.Comment, arg3 ...string) error {
	fake.updateByIdMutex.Lock()
	ret, specificReturn := fake.updateByIdReturnsOnCall[len(fake.updateByIdArgsForCall)]
	fake.updateByIdArgsForCall = append(fake.updateByIdArgsForCall, struct {
		arg1 context.Context
		arg2 model.Comment
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.UpdateByIdStub
	fakeReturns := fake.updateByIdReturns
	fake.recordInvocation("UpdateById", []interface{}{arg1, arg2, arg3})
	fake.updateByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) UpdateByIdCallCount() int {
	fake.updateByIdMutex.RLock()
	defer fake.updateByIdMutex.RUnlock()
	return len(fake.updateByIdArgsForCall)
}

func (fake *FakeCommentRepository) UpdateByIdCalls(stub func(context.Context, model.Comment, ...string) error) {
	fake.updateByIdMutex.Lock()
	defer fake.updateByIdMutex.Unlock()
	fake.UpdateByIdStub = stub
}

func (fake *FakeCommentRepository) UpdateByIdArgsForCall(i int) (context.Context, model.Comment, []string) {
	fake.updateByIdMutex.RLock()
	defer fake.updateByIdMutex.RUnlock()
	argsForCall := fake.updateByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCommentRepository) UpdateByIdReturns(result1 error) {
	fake.updateByIdMutex.Lock()
	defer fake.updateByIdMutex.Unlock()
	fake.UpdateByIdStub = nil
	fake.updateByIdReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) UpdateByIdReturnsOnCall(i int, result1 error) {
	fake.updateByIdMutex.Lock()
	defer fake.updateByIdMutex.Unlock()
	fake.UpdateByIdStub = nil
	if fake.updateByIdReturnsOnCall == nil {
		fake.updateByIdReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateByIdReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.deleteByArticleIdMutex.RLock()
	defer fake.deleteByArticleIdMutex.RUnlock()
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	fake.updateByIdMutex.RLock()
	defer fake.updateByIdMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCommentRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.CommentRepository = new(FakeCommentRepository)
