// Code generated by counterfeiter. DO NOT EDIT.
package domainfakes

import (
	"context"
	"realworld-go/domain"
	"realworld-go/domain/model"
	"sync"
)

type FakeCommentRepository struct {
	DeleteByIDStub        func(context.Context, string) error
	deleteByIDMutex       sync.RWMutex
	deleteByIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteByIDReturns struct {
		result1 error
	}
	deleteByIDReturnsOnCall map[int]struct {
		result1 error
	}
	FindAllByArticleIDStub        func(context.Context, domain.FindAllCommentParam, ...string) ([]model.Comment, error)
	findAllByArticleIDMutex       sync.RWMutex
	findAllByArticleIDArgsForCall []struct {
		arg1 context.Context
		arg2 domain.FindAllCommentParam
		arg3 []string
	}
	findAllByArticleIDReturns struct {
		result1 []model.Comment
		result2 error
	}
	findAllByArticleIDReturnsOnCall map[int]struct {
		result1 []model.Comment
		result2 error
	}
	UpSertByIDStub        func(context.Context, model.Comment, ...string) error
	upSertByIDMutex       sync.RWMutex
	upSertByIDArgsForCall []struct {
		arg1 context.Context
		arg2 model.Comment
		arg3 []string
	}
	upSertByIDReturns struct {
		result1 error
	}
	upSertByIDReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCommentRepository) DeleteByID(arg1 context.Context, arg2 string) error {
	fake.deleteByIDMutex.Lock()
	ret, specificReturn := fake.deleteByIDReturnsOnCall[len(fake.deleteByIDArgsForCall)]
	fake.deleteByIDArgsForCall = append(fake.deleteByIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteByIDStub
	fakeReturns := fake.deleteByIDReturns
	fake.recordInvocation("DeleteByID", []interface{}{arg1, arg2})
	fake.deleteByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) DeleteByIDCallCount() int {
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	return len(fake.deleteByIDArgsForCall)
}

func (fake *FakeCommentRepository) DeleteByIDCalls(stub func(context.Context, string) error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = stub
}

func (fake *FakeCommentRepository) DeleteByIDArgsForCall(i int) (context.Context, string) {
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	argsForCall := fake.deleteByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCommentRepository) DeleteByIDReturns(result1 error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = nil
	fake.deleteByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) DeleteByIDReturnsOnCall(i int, result1 error) {
	fake.deleteByIDMutex.Lock()
	defer fake.deleteByIDMutex.Unlock()
	fake.DeleteByIDStub = nil
	if fake.deleteByIDReturnsOnCall == nil {
		fake.deleteByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) FindAllByArticleID(arg1 context.Context, arg2 domain.FindAllCommentParam, arg3 ...string) ([]model.Comment, error) {
	fake.findAllByArticleIDMutex.Lock()
	ret, specificReturn := fake.findAllByArticleIDReturnsOnCall[len(fake.findAllByArticleIDArgsForCall)]
	fake.findAllByArticleIDArgsForCall = append(fake.findAllByArticleIDArgsForCall, struct {
		arg1 context.Context
		arg2 domain.FindAllCommentParam
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.FindAllByArticleIDStub
	fakeReturns := fake.findAllByArticleIDReturns
	fake.recordInvocation("FindAllByArticleID", []interface{}{arg1, arg2, arg3})
	fake.findAllByArticleIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCommentRepository) FindAllByArticleIDCallCount() int {
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	return len(fake.findAllByArticleIDArgsForCall)
}

func (fake *FakeCommentRepository) FindAllByArticleIDCalls(stub func(context.Context, domain.FindAllCommentParam, ...string) ([]model.Comment, error)) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = stub
}

func (fake *FakeCommentRepository) FindAllByArticleIDArgsForCall(i int) (context.Context, domain.FindAllCommentParam, []string) {
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	argsForCall := fake.findAllByArticleIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCommentRepository) FindAllByArticleIDReturns(result1 []model.Comment, result2 error) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = nil
	fake.findAllByArticleIDReturns = struct {
		result1 []model.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeCommentRepository) FindAllByArticleIDReturnsOnCall(i int, result1 []model.Comment, result2 error) {
	fake.findAllByArticleIDMutex.Lock()
	defer fake.findAllByArticleIDMutex.Unlock()
	fake.FindAllByArticleIDStub = nil
	if fake.findAllByArticleIDReturnsOnCall == nil {
		fake.findAllByArticleIDReturnsOnCall = make(map[int]struct {
			result1 []model.Comment
			result2 error
		})
	}
	fake.findAllByArticleIDReturnsOnCall[i] = struct {
		result1 []model.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeCommentRepository) UpSertByID(arg1 context.Context, arg2 model.Comment, arg3 ...string) error {
	fake.upSertByIDMutex.Lock()
	ret, specificReturn := fake.upSertByIDReturnsOnCall[len(fake.upSertByIDArgsForCall)]
	fake.upSertByIDArgsForCall = append(fake.upSertByIDArgsForCall, struct {
		arg1 context.Context
		arg2 model.Comment
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.UpSertByIDStub
	fakeReturns := fake.upSertByIDReturns
	fake.recordInvocation("UpSertByID", []interface{}{arg1, arg2, arg3})
	fake.upSertByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCommentRepository) UpSertByIDCallCount() int {
	fake.upSertByIDMutex.RLock()
	defer fake.upSertByIDMutex.RUnlock()
	return len(fake.upSertByIDArgsForCall)
}

func (fake *FakeCommentRepository) UpSertByIDCalls(stub func(context.Context, model.Comment, ...string) error) {
	fake.upSertByIDMutex.Lock()
	defer fake.upSertByIDMutex.Unlock()
	fake.UpSertByIDStub = stub
}

func (fake *FakeCommentRepository) UpSertByIDArgsForCall(i int) (context.Context, model.Comment, []string) {
	fake.upSertByIDMutex.RLock()
	defer fake.upSertByIDMutex.RUnlock()
	argsForCall := fake.upSertByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCommentRepository) UpSertByIDReturns(result1 error) {
	fake.upSertByIDMutex.Lock()
	defer fake.upSertByIDMutex.Unlock()
	fake.UpSertByIDStub = nil
	fake.upSertByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) UpSertByIDReturnsOnCall(i int, result1 error) {
	fake.upSertByIDMutex.Lock()
	defer fake.upSertByIDMutex.Unlock()
	fake.UpSertByIDStub = nil
	if fake.upSertByIDReturnsOnCall == nil {
		fake.upSertByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upSertByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCommentRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteByIDMutex.RLock()
	defer fake.deleteByIDMutex.RUnlock()
	fake.findAllByArticleIDMutex.RLock()
	defer fake.findAllByArticleIDMutex.RUnlock()
	fake.upSertByIDMutex.RLock()
	defer fake.upSertByIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCommentRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.CommentRepository = new(FakeCommentRepository)
